# Generated by Django 3.2.9 on 2021-11-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=True, max_length=40),
            preserve_default=False,
        ),
    ]
