# Generated by Django 3.2.9 on 2021-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('No Gender', 'No Gender'), ('Male', 'Male'), ('Female', 'Female')], default='No Gender', max_length=20),
        ),
    ]
