# Generated by Django 3.2.9 on 2021-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/default_images/default.jpg', upload_to='profile/'),
        ),
    ]
