# Generated by Django 3.2.9 on 2021-12-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
