# Generated by Django 3.2.9 on 2021-12-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
