# Generated by Django 3.2.9 on 2021-11-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-commented_on'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('post_thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
