# Generated by Django 3.2.9 on 2021-11-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comment_message_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
