# Generated by Django 3.2.9 on 2021-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
