# Generated by Django 3.2.9 on 2022-01-06 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20220106_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MassageModel',
            new_name='MessegeModel',
        ),
    ]
