# Generated by Django 3.2.9 on 2022-01-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_massagemodel_messegemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messegemodel',
            old_name='message_image',
            new_name='messege_image',
        ),
    ]
