# Generated by Django 3.2.9 on 2022-01-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_message_image_messegemodel_messege_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmodel',
            old_name='receiver',
            new_name='reciever',
        ),
    ]
