# Generated by Django 3.2.9 on 2021-11-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
